import { Geist, Geist_Mono } from "next/font/google";
import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core';
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>EscapeGame</title>
        <meta name="description" content="Generated by create next app" />
      </head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MantineProvider
          defaultColorScheme="dark"
          theme={{
            fontFamily: 'var(--font-geist-sans)',
            headings: { fontFamily: 'var(--font-geist-sans)' },
          }}
        >
          <Suspense>{children}</Suspense>
        </MantineProvider>
      </body>
    </html >
  );
}
